pipeline:
  composer-sa-checks:
    image: fpfis/drone-composer-sa-checker
    lock_file: composer.lock

  install:
    image: fpfis/php71-dev
    commands:
      - composer global require hirak/prestissimo
      - composer install --ansi

  phpcs:
    image: fpfis/php71-dev
    commands:
      - ./vendor/bin/phpcs

  build-phar:
    image: phpdrone/phar-composer
    output: ghcli.phar
  
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: ghcli.phar 
    checksum:
      - sha256
    when:
      event: tag
