pipeline:
  composer-sa-checks:
    image: fpfis/drone-composer-sa-checker
    lock_file: composer.lock

  install:
    image: fpfis/php71-dev
    commands:
      - composer install --ansi

  phpcs:
    image: fpfis/php71-dev
    commands:
      - ./vendor/bin/phpcs

  build-dev:
    image: fpfis/php71-dev
    commands: 
      - ./vendor/bin/phar-composer --ansi build . ghcli-dev.phar
    when:
      event: push

  build-release:
    image: fpfis/php71-dev
    commands:
      - wget https://github.com/clue/phar-composer/releases/download/v1.0.0/phar-composer.phar -O /tmp/phar-composer
      - composer install --ansi --no-dev 
      - php /tmp/phar-composer --ansi build . ghcli.phar
    when:
      event: tag

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: ghcli.phar 
    checksum:
      - sha256
    when:
      event: tag
