pipeline:
  composer-sa-checks:
    image: fpfis/drone-composer-sa-checker
    lock_file: composer.lock

  install:
    image: phpdrone/composer:php56-latest
    commands:
      - composer install --ansi

  phpcs:
    image: phpdrone/composer:php56-latest
    commands:
      - ./vendor/bin/phpcs

  build-phar:
    image: phpdrone/phar-composer
    output: ghcli.phar

  build-docker:
    image: plugins/docker
    repo: gboo/ghcli
    secrets: [ docker_username, docker_password ]
    when:
      event: push 
  
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: ghcli.phar 
    checksum:
      - sha256
    when:
      event: tag
